version: '3'
services:
  apache:
    image: fusengine/apache-php:alpine-php7.4-dev
    ports:
      - '8080:80'
    volumes:
      - ./project:/app/web
    networks:
      - my_network

  mysql:
    image: mysql:latest
    command: '--default-authentication-plugin=mysql_native_password'
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_DATABASE: 'myspace_db'
      MYSQL_USER: 'sqluser'
      MYSQL_PASSWORD: '123456'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    links:
      - mysql
    ports:
      - '8082:80'
    environment:
      PMA_HOST: 'mysql'
      MYSQL_ROOT_PASSWORD: 'root_password'
    networks:
      - my_network

networks:
  my_network:

volumes:
  mysql_data:
